title: Huanyu Yin
name: Huanyu Yin
description: Academic Homepage
url: "https://checkandraise.github.io"

markdown: kramdown
theme: minima

include:
  - _pages

header_pages:
  - index.md
  - _pages/research.md
  - _pages/cv.md
